#é¿ê—ì˙ÉeÅ[ÉuÉã
CREATE TABLE ACHIEVE_DAY_TBL (
	WORK_ID	     INT,
	USER_NO	     INT,
  BEGIN_YMD	       VARCHAR(10),
	END_YMD	         VARCHAR(10),
	FINISH_KBN VARCHAR(1),
	CONSTRAINT ACHIEVE_DAY_TBL PRIMARY KEY(WORK_ID, USER_NO)
);
