#シークエンス管理テーブル
CREATE TABLE SEQUENCE (
  SEQ_NAME VARCHAR(50) PRIMARY KEY,
  CURRENT_VAL INT NOT NULL,
  INCREMENT INT NOT NULL
);

#シークエンスの追加
INSERT INTO SEQUENCE VALUES ('PROJECT_ID', 0, 1);
INSERT INTO SEQUENCE VALUES ('WORK_ID', 0, 1);
INSERT INTO SEQUENCE VALUES ('USER_NO', 0, 1);

#現在のシークエンス番号を取得する
DELIMITER $
CREATE FUNCTION currval (seqName VARCHAR(50))
    RETURNS INTEGER
    LANGUAGE SQL
    DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    DECLARE value INTEGER;
    SET value = 0;
    SELECT CURRENT_VAL INTO value
        FROM SEQUENCE
        WHERE SEQ_NAME = seqName;
    RETURN value;
END
$
DELIMITER ;

#次のシークエンス番号を取得する
DELIMITER $
CREATE FUNCTION nextval (seqName VARCHAR(50))
    RETURNS INTEGER
    LANGUAGE SQL
    DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    UPDATE SEQUENCE
    SET CURRENT_VAL = CURRENT_VAL + INCREMENT
    WHERE SEQ_NAME = seqName;
    RETURN currval(seqName);
END
$
DELIMITER ;
